apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: sova
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: sova
spec:
  selector:
    app.kubernetes.io/name: app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
