apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sova
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: sova
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
